import React from "react";
import SketchTorusHero from './sketches/sketch'
import SketchTorus from './sketches/sketch-torus'
import './App.css';

function App() {
  return (
    <>
      <header>
        <div className="container">
          <div className="logo">x</div>
          <div className="menu">burger</div>
        </div>
      </header>
      <main>
        <section className="canvas-sketch">
          <SketchTorusHero />
          <section className="hero-text">
            <h1>TORUS EXPERIMENT</h1>
          </section>
        </section>
        <section className="about">
          <div className="container">
            <div className="row">
              <div className="about-img">imagem</div>
              <div className="about-text">
                <h2>Torus</h2>
                <p>
                  In geometry, a torus (plural tori) is a surface of revolution generated by revolving a circle in three-dimensional space about an axis that is coplanar with the circle.
                  <br/>
                  <br/>
                  If the axis of revolution does not touch the circle, the surface has a ring shape and is called a torus of revolution. If the axis of revolution is tangent to the circle, the surface is a horn torus. If the axis of revolution passes twice through the circle, the surface is a spindle torus. If the axis of revolution passes through the center of the circle, the surface is a degenerate torus, a sphere. If the revolved curve is not a circle, the surface is a related shape, a toroid.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="canvas-sketch">
          <SketchTorus />
        </section>
        <section className="carousel">
          <div className="container">
            carousel
          </div>
        </section>
      </main>
      <footer>
        this is the footer
      </footer>
    </>
  );
}

export default App;